# Generated by Django 6.0 on 2025-12-28 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('abbrev', models.CharField(max_length=10)),
                ('conference', models.CharField(max_length=20)),
                ('division', models.CharField(max_length=20)),
                ('external_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('position', models.CharField(max_length=1)),
                ('shoots_catches', models.CharField(max_length=1)),
                ('external_id', models.IntegerField(unique=True)),
                ('teams', models.ManyToManyField(related_name='players', to='nhlApp.team')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.CharField(max_length=10)),
                ('games_played', models.IntegerField()),
                ('goals', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('points', models.IntegerField()),
                ('plus_minus', models.IntegerField()),
                ('shots', models.IntegerField()),
                ('shooting_pct', models.FloatField()),
                ('pp_goals', models.IntegerField()),
                ('pp_points', models.IntegerField()),
                ('sh_goals', models.IntegerField()),
                ('sh_points', models.IntegerField()),
                ('ev_goals', models.IntegerField()),
                ('ev_points', models.IntegerField()),
                ('time_on_ice_per_game', models.FloatField()),
                ('faceoff_win_pct', models.FloatField(blank=True, null=True)),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhlApp.player')),
            ],
            options={
                'unique_together': {('player', 'season_id')},
            },
        ),
    ]
