# Generated by Django 6.0 on 2025-12-28 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='external_id',
            field=models.IntegerField(),
        ),
    ]
