# Generated by Django 6.0 on 2025-12-28 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlApp', '0002_alter_team_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playerseasonstat',
            name='shooting_pct',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
