# Generated by Django 6.0 on 2026-01-06 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nhlApp', '0003_alter_playerseasonstat_shooting_pct'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='teams',
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='ev_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='ev_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='plus_minus',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='pp_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='pp_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='sh_goals',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='sh_points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='shots',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='playerseasonstat',
            name='time_on_ice_per_game',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PlayerSeasonTeam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_season_stat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teams', to='nhlApp.playerseasonstat')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nhlApp.team')),
            ],
            options={
                'unique_together': {('player_season_stat', 'team')},
            },
        ),
    ]
